version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fetii
      POSTGRES_PASSWORD: fetii
      POSTGRES_DB: fetii
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://fetii:fetii@db:5432/fetii
      FETII_XLSX: /data/FetiiAI_Data_Austin.xlsx
      # (no OpenAI/Gemini vars needed now)
    volumes:
      - ./data:/data:ro
    depends_on:
      - db
    ports:
      - "8501:8501"
    command: >
      bash -lc "
        python db_load.py &&
        streamlit run main.py --server.port 8501 --server.address 0.0.0.0
      "

volumes:
  pgdata:
